### ISSUE TITLE
报错误

### ISSUE THREAD

**Issue by qq530409403** [Aruelius/tieba_sign#1]
root@seedbox:/home/my/tieba_sign# python3 tieba.py
Traceback (most recent call last):
  File "tieba.py", line 278, in <module>
    main()
  File "tieba.py", line 243, in main
    username = accounts[user]['username']
KeyError: 'xxx'
root@seedbox:/home/my/tieba_sign# v

而且我的密码里面有两个点....

**Comment by Aruelius** [comment]
`KeyError: 'xxx'`
你这应该是users填了xxx吧。

**Comment by qq530409403** [comment]
填了我的用户名  难道不应该填吗   XXX是我的用户名  。。

**Comment by Aruelius** [comment]
把你在config.py填写的内容截个图。

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55795397-42c45e00-5afa-11e9-96b4-b9b71d61b804.png)

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/55795441-5cfe3c00-5afa-11e9-9f2f-edec7370531a.png)
 这里要对应你填的用户名。

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55795811-3391e000-5afb-11e9-9922-ade0028b1c7b.png)

**Comment by qq530409403** [comment]
变成这样了。。。

**Comment by Aruelius** [comment]
看README的使用教程
https://github.com/MikuShare/tieba_sign#%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8Bcentos
注意Centos跟Ubuntu的区别。

**Comment by qq530409403** [comment]
pkill chrome*  这个指令用了啊  还是报错  是用Ubuntu sudo apt-get install chromium-browser  安装的啊

**Comment by Aruelius** [comment]
2、安装Chromedriver
这一步以及下面的也要进行。

**Comment by qq530409403** [comment]
好了  昨天这报了个错误![123](https://user-images.githubusercontent.com/26843029/55797233-7acda000-5afe-11e9-8c74-39f9726d9d3e.png)  验证码没识别。。

**Comment by qq530409403** [comment]
而且   我用pip install -r requirements.txt 这个报错误  pip3 install -r requirements.txt  用这个装上的

**Comment by Aruelius** [comment]
这里验证码要自己看code.png这个图片，然后自己输入验证码才行。
pip3对应python3。

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55798883-9470e680-5b02-11e9-8ffe-25a223a97402.png)

**Comment by Aruelius** [comment]
遇到有关Chrome的问题直接运行：pkill chrome*

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55799427-f4b45800-5b03-11e9-90dd-e00dfbee1127.png)

**Comment by qq530409403** [comment]
都试了

**Comment by Aruelius** [comment]
把/tmp/codingpy.png发来看看

**Comment by qq530409403** [comment]
![codingpy](https://user-images.githubusercontent.com/26843029/55799984-372a6480-5b05-11e9-85f4-6d380ab3e2c4.png)

**Comment by Aruelius** [comment]
帐号填写的是登录的帐号：手机号，邮箱，用户名。
你这填的啥

**Comment by qq530409403** [comment]
用户名

**Comment by qq530409403** [comment]
用户名是中文的

**Comment by Aruelius** [comment]
填登录手机号或者邮箱。

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55800957-82457700-5b07-11e9-9be6-daedacbed5ab.png)

**Comment by qq530409403** [comment]
手机号

**Comment by Aruelius** [comment]
你先去tieba.baidu.com登录，这里填的什么帐号密码能登录，脚本里就填什么。

**Comment by Aruelius** [comment]
肯定是帐号密码填错了。

**Comment by qq530409403** [comment]
我的密码后面有两个点  ..

**Comment by Aruelius** [comment]
username = 'miku@qq.com'
password = 'miku..'
帐号密码是这样填的，你肯定填错了，自己查一下。

**Comment by qq530409403** [comment]
肯定没错
![123](https://user-images.githubusercontent.com/26843029/55801426-a2296a80-5b08-11e9-85b3-7f72ff11a0fc.png)

**Comment by MikuShare** [comment]
users里面填写的是你来分辨的用户名，你填写的15810840075要跟上面填的一样，username后面填的是登录的帐号，一般是邮箱手机号，password后面是密码。

**Comment by qq530409403** [comment]
上面写的一样

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/55801865-94281980-5b09-11e9-9615-10f7565c7861.png)
![image](https://user-images.githubusercontent.com/25380989/55801889-a2763580-5b09-11e9-9168-b8cd09baf7a7.png)

**Comment by Aruelius** [comment]
我的用户名叫做MikuShare，我登录的时候也可以用MikuShare，所以这三个可以填一样的。或者我第三个MikuShare可以填我的邮箱。你再确认一下帐号密码有没有填错。

**Comment by Aruelius** [comment]
然后再试一次登录，如果还报错，就把/tmp/coding.png再发一次。

**Comment by qq530409403** [comment]
codingpy.png并没有生成新的文件

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55802308-8a52e600-5b0a-11e9-8539-bc83ba272928.png)  把手机号那条信息帮忙删了  谢谢

**Comment by Aruelius** [comment]
pkill chrome*

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/55802617-2d0b6480-5b0b-11e9-857c-3cf126469777.png)

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/55802778-84a9d000-5b0b-11e9-9846-f87131aa7d01.png)
刚刚在Ubuntu18.04上测试了一遍，没有问题。
你把现在的代码删掉，再重新git一下代码运行试试。

**Comment by qq530409403** [comment]
OK 好了  谢谢
