### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by nicolasmeng** [Aruelius/tieba_sign#10]
已经成功签到了，看提示可能是遇到验证码就报这个错误
如下图：

![image](https://user-images.githubusercontent.com/4972409/68919273-5af50d80-07ac-11ea-8b96-66193a7ac52a.png)

**Comment by nicolasmeng** [comment]
是同一次执行的第二张错误图
![image](https://user-images.githubusercontent.com/4972409/68919648-d5725d00-07ad-11ea-9bac-fc0c8ca182e5.png)

**Comment by nicolasmeng** [comment]
第三张，看起来跟第一张一样
![image](https://user-images.githubusercontent.com/4972409/68919740-25e9ba80-07ae-11ea-8948-e17c9e8845b9.png)

**Comment by nicolasmeng** [comment]
运行环境：win10 》CMD
python版本:anaconda3 》python3.7.0
源码未作改动，昨天第一次测试用jupyter未报这些错误，一切正常，今天用CMD报上面错误。
三张错误图，分别对应三个账号，都是在账号签到成功结尾处报错

**Comment by nicolasmeng** [comment]
刚才用jupyter运行，不报任何错误...很奇怪

**Comment by Aruelius** [comment]
你可以在报错的这一行(232)加个异常捕获，然后输出r.text，看看是个啥
`try:
    resp = r.json()
except:
    print(r.text)`

**Comment by Aruelius** [comment]
```python
try:
    resp = r.json()
except:
    print(r.text)
```

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69315785-562fce00-0c72-11ea-809b-cfffb7fa47f6.png)
1楼那个错误，今天jupyter又报了一次，2楼3楼的错误也报了一次，刚来看，还没来得及加try

**Comment by nicolasmeng** [comment]
最后报了这个错误，并且没有完成所有账号的打卡，貌似出这个错误程序就终止了
`TooManyRedirects                          Traceback (most recent call last)
<ipython-input-1-d4fa97dd85a6> in <module>()
    285     s.headers.update({'User-Agent': ua})
    286     start_time = time.time()
--> 287     main()
    288     end_time = time.time()
    289     print('总共签到{}个贴吧,耗时:{}秒'.format(len(list), int(end_time - start_time)))

<ipython-input-1-d4fa97dd85a6> in main()
    262             cookies = requests.utils.cookiejar_from_dict(load_cookies)
    263             s.cookies.update(cookies)
--> 264             if checkLogin():
    265                 print('CookieLogin : True')
    266                 tiebas = getbar()

<ipython-input-1-d4fa97dd85a6> in checkLogin()
    138 
    139 def checkLogin():
--> 140     r = s.get('https://tieba.baidu.com/f/user/json_userinfo')
    141     try:
    142         print(r.json()['data']['user_name_weak'])

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    523 
    524         kwargs.setdefault('allow_redirects', True)
--> 525         return self.request('GET', url, **kwargs)
    526 
    527     def options(self, url, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    510         }
    511         send_kwargs.update(settings)
--> 512         resp = self.send(prep, **send_kwargs)
    513 
    514         return resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    138 
    139             if len(resp.history) >= self.max_redirects:
--> 140                 raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    141 
    142             # Release the connection back into the pool.

TooManyRedirects: Exceeded 30 redirects.`

**Comment by Aruelius** [comment]
我还是复现不了，加个异常捕获看看r.text是个啥吧。

**Comment by nicolasmeng** [comment]
今天只出了10楼那个错误
https://github.com/Aruelius/tieba_sign/issues/10#issuecomment-556955230
而且出现的账号都一样，都是一个吧也没关注的账号。

**Comment by nicolasmeng** [comment]
> 远程主机强迫关闭了一个现有的连接。
这是不是签到的太多，太快了？

`ConnectionResetError                      Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    383                     # otherwise it looks like a programming error was the cause.
--> 384                     six.raise_from(e, None)
    385         except (SocketTimeout, BaseSSLError, SocketError) as e:

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py in raise_from(value, from_value)

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    379                 try:
--> 380                     httplib_response = conn.getresponse()
    381                 except Exception as e:

C:\ProgramData\Anaconda3\lib\http\client.py in getresponse(self)
   1320             try:
-> 1321                 response.begin()
   1322             except ConnectionError:

C:\ProgramData\Anaconda3\lib\http\client.py in begin(self)
    295         while True:
--> 296             version, status, reason = self._read_status()
    297             if status != CONTINUE:

C:\ProgramData\Anaconda3\lib\http\client.py in _read_status(self)
    256     def _read_status(self):
--> 257         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    258         if len(line) > _MAXLINE:

C:\ProgramData\Anaconda3\lib\socket.py in readinto(self, b)
    588             try:
--> 589                 return self._sock.recv_into(b)
    590             except timeout:

ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

ProtocolError                             Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    444                     retries=self.max_retries,
--> 445                     timeout=timeout
    446                 )

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    366             if read is False or not self._is_method_retryable(method):
--> 367                 raise six.reraise(type(error), error, _stacktrace)
    368             elif read is not None:

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    383                     # otherwise it looks like a programming error was the cause.
--> 384                     six.raise_from(e, None)
    385         except (SocketTimeout, BaseSSLError, SocketError) as e:

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\packages\six.py in raise_from(value, from_value)

C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    379                 try:
--> 380                     httplib_response = conn.getresponse()
    381                 except Exception as e:

C:\ProgramData\Anaconda3\lib\http\client.py in getresponse(self)
   1320             try:
-> 1321                 response.begin()
   1322             except ConnectionError:

C:\ProgramData\Anaconda3\lib\http\client.py in begin(self)
    295         while True:
--> 296             version, status, reason = self._read_status()
    297             if status != CONTINUE:

C:\ProgramData\Anaconda3\lib\http\client.py in _read_status(self)
    256     def _read_status(self):
--> 257         line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
    258         if len(line) > _MAXLINE:

C:\ProgramData\Anaconda3\lib\socket.py in readinto(self, b)
    588             try:
--> 589                 return self._sock.recv_into(b)
    590             except timeout:

ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-2-2341f6f09e90> in <module>()
    288     s.headers.update({'User-Agent': ua})
    289     start_time = time.time()
--> 290     main()
    291     end_time = time.time()
    292     print('总共签到{}个贴吧,耗时:{}秒'.format(len(list), int(end_time - start_time)))

<ipython-input-2-2341f6f09e90> in main()
    265             cookies = requests.utils.cookiejar_from_dict(load_cookies)
    266             s.cookies.update(cookies)
--> 267             if checkLogin():
    268                 print('CookieLogin : True')
    269                 tiebas = getbar()

<ipython-input-2-2341f6f09e90> in checkLogin()
    138 
    139 def checkLogin():
--> 140     r = s.get('https://tieba.baidu.com/f/user/json_userinfo')
    141     try:
    142         print(r.json()['data']['user_name_weak'])

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    523 
    524         kwargs.setdefault('allow_redirects', True)
--> 525         return self.request('GET', url, **kwargs)
    526 
    527     def options(self, url, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    510         }
    511         send_kwargs.update(settings)
--> 512         resp = self.send(prep, **send_kwargs)
    513 
    514         return resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    220                     proxies=proxies,
    221                     allow_redirects=False,
--> 222                     **adapter_kwargs
    223                 )
    224 

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    620 
    621         # Send the request
--> 622         r = adapter.send(request, **kwargs)
    623 
    624         # Total elapsed time of the request (approximately)

C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    493 
    494         except (ProtocolError, socket.error) as err:
--> 495             raise ConnectionError(err, request=request)
    496 
    497         except MaxRetryError as e:

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))`

**Comment by nicolasmeng** [comment]
一秒钟签到一次，怎么改？我想牺牲速度看看

**Comment by nicolasmeng** [comment]
> def sign(tieba):
>     tbs = gettbs()
>     data = {
>         'ie':'utf-8',
>         'kw':tieba,
>         'tbs':tbs
>     }
>     r = s.post('http://tieba.baidu.com/sign/add', data = data)
>     time.sleep( 1 )
>     print ("End : %s" % time.ctime())



这里加sleep并不起作用，打印出来一秒执行很多次

**Comment by Aruelius** [comment]
很明显 不能 ，因为是多线程同步，这样改
```python
    for tieba in threads:
        tieba.start()
        time.sleep(1.5)
```

**Comment by nicolasmeng** [comment]
```
状态:亲，你之前已经签过了
状态:亲，你之前已经签过了
贴吧:德州	状态:亲，你之前已经签过了
End : Tue Nov 26 14:24:24 2019
End : Tue Nov 26 14:24:25 2019
End : Tue Nov 26 14:24:26 2019
End : Tue Nov 26 14:24:27 2019
End : Tue Nov 26 14:24:28 2019
End : Tue Nov 26 14:24:29 2019
End : Tue Nov 26 14:24:30 2019
```
按你说的改了，打印了一下时间，发现还是运行飞快，时间是叠在一起打印出来

**Comment by nicolasmeng** [comment]
> for tieba in threads:
>         tieba.join()
>         time.sleep( 1 )
>         print ("End : %s" % time.ctime())

**Comment by Aruelius** [comment]
`tieba.start()` 下面

**Comment by nicolasmeng** [comment]
> 贴吧:浮山	状态:签到成功!
> End : Wed Nov 27 15:25:30 2019
> 贴吧:襄汾	状态:签到成功!
> End : Wed Nov 27 15:25:31 2019
> 贴吧:原平	状态:签到成功!
> End : Wed Nov 27 15:25:32 2019

```

---------------------------------------------------------------------------
TooManyRedirects                          Traceback (most recent call last)
<ipython-input-1-f68f5b3f96a9> in <module>()
    292     s.headers.update({'User-Agent': ua})
    293     start_time = time.time()
--> 294     main()
    295     end_time = time.time()
    296 

<ipython-input-1-f68f5b3f96a9> in main()
    269             cookies = requests.utils.cookiejar_from_dict(load_cookies)
    270             s.cookies.update(cookies)
--> 271             if checkLogin():
    272                 print('CookieLogin : True')
    273                 tiebas = getbar()

<ipython-input-1-f68f5b3f96a9> in checkLogin()
    139 
    140 def checkLogin():
--> 141     r = s.get('https://tieba.baidu.com/f/user/json_userinfo')
    142     try:
    143         print(r.json()['data']['user_name_weak'])

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in get(self, url, **kwargs)
    523 
    524         kwargs.setdefault('allow_redirects', True)
--> 525         return self.request('GET', url, **kwargs)
    526 
    527     def options(self, url, **kwargs):

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    510         }
    511         send_kwargs.update(settings)
--> 512         resp = self.send(prep, **send_kwargs)
    513 
    514         return resp

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in <listcomp>(.0)
    642 
    643         # Resolve redirects if allowed.
--> 644         history = [resp for resp in gen] if allow_redirects else []
    645 
    646         # Shuffle things around if there's history.

C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py in resolve_redirects(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)
    138 
    139             if len(resp.history) >= self.max_redirects:
--> 140                 raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    141 
    142             # Release the connection back into the pool.

TooManyRedirects: Exceeded 30 redirects.

```

**Comment by nicolasmeng** [comment]
今天就报了这个一个错误，然后就终止了。成功打卡将近400个

**Comment by Aruelius** [comment]
建议每天三个时间段自动签到，每天签到三次。

**Comment by nicolasmeng** [comment]
百度很奇怪，我今天间隔10秒钟签到一次，还是在将近400个的时候出现上面的错误...

一天3次的话，第二次开始会有大量重复签到，是重复发出签到请求么？还是发现已经签到了，就给出提示？

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/69784252-525ef700-11f0-11ea-8d20-08450325db01.png)

我的签到没有问题，应该就是你签到的吧太多了，你可以改一下代码，到了两百个就停10分钟。

提示之前已经签到就是重复签到，这个问题不大。

**Comment by nicolasmeng** [comment]
过了50分钟了，我把已经签到的账号删掉，重新运行，直接蹦出那个错误...连账号登陆信息都没有的

**Comment by Aruelius** [comment]
应该是同IP访问太多，那就要用到代理池了。

**Comment by nicolasmeng** [comment]
重启路由器来切换IP也不行...

**Comment by Aruelius** [comment]
你确定用的最新版么

**Comment by nicolasmeng** [comment]
应该是吧，我看README.md文件里有下面
```
### ChangeLog

2019年10月12日

1. 登录块从账号密码登陆改成了扫码登陆，因为账号密码登陆需要拉动滑块验证
2. 验证码签到这块改善了代码，一般情况下不会再出现问题
3. 代码逻辑有改善
```

**Comment by Aruelius** [comment]
目前我的两个账号是没有任何问题的。恕对你的问题无能为力，测试无从下手。

**Comment by nicolasmeng** [comment]
好吧
我把请求这个链接的语句注释掉：https://tieba.baidu.com/f/user/json_userinfo 
然后报请求这个链接的错误：http://tieba.baidu.com/f/like/mylike?pn=
错误跟上面一样：TooManyRedirects: Exceeded 30 redirects.

不知道怎么定位我这台电脑的，IP换了，账号换了，用电脑管家清理了缓存，一样报错

**Comment by Aruelius** [comment]
目前解决方法：每天分三个时间段执行脚本。

**Comment by nicolasmeng** [comment]
https://github.com/MoeNetwork/Tieba-Cloud-Sign
我之前用过这个签到，iphone接口没有数量限制，但是它没解决验证码问题，供作者参考

**Comment by Aruelius** [comment]
刚刚更新了几处代码，或许可以解决。你把代码更新一下 重新试试。

**Comment by nicolasmeng** [comment]
TooManyRedirects: Exceeded 30 redirects.
还是这个错误，应该是PC端被限制请求次数了

**Comment by Aruelius** [comment]
用CMD执行，报错截图。

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69790138-e46cfc80-11fc-11ea-9d7f-6d1f1fe6dbf1.png)

**Comment by Aruelius** [comment]
> https://github.com/MoeNetwork/Tieba-Cloud-Sign
> 我之前用过这个签到，iphone接口没有数量限制，但是它没解决验证码问题，供作者参考

我试过用手机端的接口签到，第二次签到会报错。

**Comment by Aruelius** [comment]
在
```python
def checkLogin():
```
下面添加一行
```python
def checkLogin():
    print(s.headers)
```
再截图

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69790840-2fd3da80-11fe-11ea-84ed-11f7012f6b41.png)
![image](https://user-images.githubusercontent.com/4972409/69790887-4712c800-11fe-11ea-815c-f4547a90e3ac.png)

**Comment by nicolasmeng** [comment]
我放错地方了吧

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69791056-aa045f00-11fe-11ea-9e2a-c8e6eec1cb8a.png)

**Comment by nicolasmeng** [comment]
```
`//签到一个贴吧，只需要替换$bduss,fid,kw
    public function daKa($bduss,$fid,$kw)
    {
        //$url = 'http://tieba.baidu.com/mo/m?kw=书战&fid=5553103';
        $ch = new Wcurl('http://c.tieba.baidu.com/c/c/forum/sign', array('Content-Type: application/x-www-form-urlencoded','User-Agent: Fucking iPhone/1.0 BadApple/99.1'));
        $ch->addcookie("BDUSS=".$bduss);
        $temp = array(
            'BDUSS' => $bduss,
            '_client_id' => '03-00-DA-59-05-00-72-96-06-00-01-00-04-00-4C-43-01-00-34-F4-02-00-BC-25-09-00-4E-36',
            '_client_type' => '4',
            '_client_version' => '1.2.1.17',
            '_phone_imei' => '540b43b59d21b7a4824e1fd31b08e9a6',
            'fid' => $fid,
            'kw' => $kw,
            'net_type' => '3',
            'tbs' => $this->getTbs($bduss)
        );
        $x = '';
        foreach($temp as $k=>$v) {
            $x .= $k.'='.$v;
        }
        $temp['sign'] = strtoupper(md5($x.'tiebaclient!!!'));
        return $ch->post($temp);
    }`
```

这个是我说的苹果接口，可能是贴吧APP的

**Comment by Aruelius** [comment]
再把
```python
print(s.headers)
```
改成
```python
print(s.cookies)
```
**注意遮挡部分cookie**

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69791372-5cd4bd00-11ff-11ea-9951-eb2debe23e48.png)

**Comment by Aruelius** [comment]
1.有可能是cookie少了，不知道你是怎么登陆的。
2.修改checkLogin函数：
```python
def checkLogin():
    r = s.get('https://tieba.baidu.com/f/user/json_userinfo')
    try:
        print(r.json()['data']['user_name_weak'])
        return True
    except:
        return False
```
改成：
```python
def checkLogin():
    r = s.get('http://tieba.baidu.com/dc/common/tbs')
    rsp = r.json()
    return True if rsp['is_login'] == 1 else False
```

**Comment by nicolasmeng** [comment]
![image](https://user-images.githubusercontent.com/4972409/69793966-5c8af080-1204-11ea-88cf-6e74f1dd44d0.png)

**Comment by Aruelius** [comment]
你的cookie出问题了。

**Comment by nicolasmeng** [comment]
> {"BDUSS":"sdzA0ZVRSTGdlMG5EUVhZfn5ub3dKOVpkRVFBQUFBJCQAAAAAAAAAAAEAAADRFU5COTm25L2-sMG1xLuoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADCarl0wmq5dQX","PTOKEN":"6d16ee149cec0d79f2","STOKEN":"1cb42152f77103a5826249b34775f756e0d8131e5e340f8218ab","BAIDUID":"8FF15AB9B1FA8CA2CE:FG=1"}

**Comment by nicolasmeng** [comment]
字符串里删了些，但是格式就这样

**Comment by Aruelius** [comment]
必须使用脚本生成的cookie，才能正常多个账号一起签到，否则的话，就会这样报错。
你应该是自己填的cookie。

**Comment by nicolasmeng** [comment]
对的，自己填的。从数据库导出来的

**Comment by Aruelius** [comment]
把cookie文件全删了，然后按照脚本的登陆流程来，问题应该就没了。

**Comment by nicolasmeng** [comment]
不是格式一样就可以么？

**Comment by Aruelius** [comment]
还少了很多值。

**Comment by nicolasmeng** [comment]
我数据库里有完整cookie，能发我完整格式么

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/69794549-6f51f500-1205-11ea-87c2-890648979412.png)

差不多得这些都在。
建议用脚本生成cookie，不要自己写cookie了。

**Comment by nicolasmeng** [comment]
确实好多，我试下

**Comment by nicolasmeng** [comment]
{"Hm_lpvt_90056b3f84f90da57dc0f40150f005d5":"","Hm_lvt_90056b3f84f90da57dc0f40150f005d5":"","BDUSS":"","PTOKEN":"","HOSUPPORT":"1","STOKEN":"","BAIDUID":"","pplogid":"","UBI":""}
这是我的完整cookie，还是那个错误

**Comment by Aruelius** [comment]
没有TIEBAUID跟TIEBA_USERTYPE

**Comment by nicolasmeng** [comment]
刚加上了，还是那个错误...

**Comment by nicolasmeng** [comment]
刚重启了电脑也不行，不是在我内存里植入东西

**Comment by Aruelius** [comment]
代码更新了一版，你可以再试试看这回会不会出错。
