### ISSUE TITLE
cookie的有效期是多长？

### ISSUE THREAD

**Issue by SYSUcarey** [Aruelius/tieba_sign#16]
成功是成功自动签到了，但我本身就只有30左右的贴吧数目，直接app也可以一键签到。
我还想自己弄一个定时器，每日凌晨帮我定时自动签到，但是这个cookie的有效期是多少。
隔几天又要重新扫码的话，也还是太麻烦了。

**Comment by Aruelius** [comment]
一般来讲百度的 Cookie 有效期可以长达一年以上。
