### ISSUE TITLE
厚脸皮建议贴

### ISSUE THREAD

**Issue by mayishidai** [Aruelius/tieba_sign#19]
自动签到挺好用的，能增加一个发帖功能么 0.0

**Comment by Aruelius** [comment]
贴吧防灌水太强了，并且发帖需要验证码的，不搞不搞

**Comment by mayishidai** [comment]
登录需要验证，发帖好像不需要，搞了一个就是发帖验证码麻烦 1620829248 邮箱：1620829248@qq.com 签名由 网易邮箱大师 定制 在2020年07月15日 10:37，Aruelius.L 写道： 贴吧防灌水太强了，并且发帖需要验证码的，不搞不搞 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
