### ISSUE TITLE
从昨天开始又开始报错误了

### ISSUE THREAD

**Issue by qq530409403** [Aruelius/tieba_sign#2]
![123](https://user-images.githubusercontent.com/26843029/56149616-8da11280-5fdf-11e9-8e28-88f9cbf1a312.png)

**Comment by qq530409403** [comment]
![123](https://user-images.githubusercontent.com/26843029/56150029-7878b380-5fe0-11e9-8aa8-b1c44789fcad.png)在最后能显示多少个贴吧

**Comment by Aruelius** [comment]
看报错是打码识别出了问题，我这里试了一下，打码服务正常运行的。

**Comment by qq530409403** [comment]
我这时好时坏  不知道为什么

**Comment by Aruelius** [comment]
网络问题吧。

**Comment by ghost** [comment]
File "tieba_sign.py", line 44
    r = s.get(f'https://passport.baidu.com/v2/api/?getapi',params = params,
                                                         ^
SyntaxError: invalid syntax

**Comment by Aruelius** [comment]
@geekxbr 有问题请重新提交Issues，这里并没有语法错误。你应该是使用过记事本打开编辑过tieba_sign.py

**Comment by ck123pm** [comment]
> @geekxbr 有问题请重新提交Issues，这里并没有语法错误。你应该是使用过记事本打开编辑过tieba_sign.py

@Aruelius  (f'xxx'=)这个语法是py3.6才支持的，我一开始也报这个错误了。README里面可以写清楚下哈，你现在写的是use python3.

**Comment by Aruelius** [comment]
> > @geekxbr 有问题请重新提交Issues，这里并没有语法错误。你应该是使用过记事本打开编辑过tieba_sign.py
> 
> @Aruelius (f'xxx'=)这个语法是py3.6才支持的，我一开始也报这个错误了。README里面可以写清楚下哈，你现在写的是use python3.

已经更新README
