### ISSUE TITLE
tieba_sign.py 执行报错

### ISSUE THREAD

**Issue by ghost** [Aruelius/tieba_sign#4]
在上一个issue给作者反馈,并没有修改任何该python文件除了accounts字典之外的内容, 我先后使用python2和pythpn3执行都是语法错误, 环境为阿里云 ubuntu16.04 server , 可能是我没有理解 需要如何配置账户?我只需要配置一个贴吧账户即可,使用vim修改了配置文件,将贴吧账户名和密码填入了配置文件的字典键值对中. 望作者答疑. 

`python3 tieba_sign.py
  File "tieba_sign.py", line 44
    r = s.get(f'https://passport.baidu.com/v2/api/?getapi', params = params,
                                                         ^
SyntaxError: invalid syntax
`
`python2 tieba_sign.py
  File "tieba_sign.py", line 44
    r = s.get(f'https://passport.baidu.com/v2/api/?getapi', params = params,
                                                         ^
SyntaxError: invalid syntax`

**Comment by Aruelius** [comment]
报错截图.

**Comment by yyltwin** [comment]
> 在上一个issue给作者反馈,并没有修改任何该python文件除了accounts字典之外的内容, 我先后使用python2和pythpn3执行都是语法错误, 环境为阿里云 ubuntu16.04 server , 可能是我没有理解 需要如何配置账户?我只需要配置一个贴吧账户即可,使用vim修改了配置文件,将贴吧账户名和密码填入了配置文件的字典键值对中. 望作者答疑.
> 
> `python3 tieba_sign.py File "tieba_sign.py", line 44 r = s.get(f'https://passport.baidu.com/v2/api/?getapi', params = params, ^ SyntaxError: invalid syntax `
> `python2 tieba_sign.py File "tieba_sign.py", line 44 r = s.get(f'https://passport.baidu.com/v2/api/?getapi', params = params, ^ SyntaxError: invalid syntax`

新版本语法，升级最新版本，
