### ISSUE TITLE
系统繁忙

### ISSUE THREAD

**Issue by yangchuanshuo** [Aruelius/tieba_sign#5]
请问系统繁忙 是什么原因呢？

**Comment by Aruelius** [comment]
咋还出来个系统繁忙，能截个图？

**Comment by yangchuanshuo** [comment]
> 咋还出来个系统繁忙，能截个图？
![image](https://user-images.githubusercontent.com/49244916/60390950-d31ca880-9b15-11e9-89bf-3fc414af4109.png)

**Comment by Aruelius** [comment]
看了一下，获取不到：authtoken，ltoken，lstr了，正在修复。

**Comment by Aruelius** [comment]
看了一下，你应该帐号密码填错了。
