### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by iamvicliu** [Aruelius/tieba_sign#6]
你好。我已经接收到了验证码，输入以后提示未知错误
已经发送验证码给：186*****~~
手机验证码：421820
未知错误！

再次运行，就提示目标计算机拒绝了

**Comment by Aruelius** [comment]
网络问题 别开代理。

**Comment by iamvicliu** [comment]
> 网络问题 别开代理。

感谢作者回复。
但是，我电脑没有开代理

**Comment by iamvicliu** [comment]
正在登陆：xxx
1.邮箱验证  2.手机验证
请选择登录验证方式：2
已经发送验证码给：186****xx
手机验证码：0xxx
未知错误！

想问下这个未知错误是什么原因？怎么检查

**Comment by Aruelius** [comment]
https://github.com/Aruelius/tieba_sign/blob/79f8b6b17e74c691a9d3660d14f3ce6975217521/tieba_sign.py#L268

未知错误，是我觉得没有手机号和没有邮箱的账号在登录的时候会报错的。
你可以把这一行的`except:`改成`except Exception as ee:`，
然后`print('未知错误！')`改成print(ee)，
再截个图过来。

或者干脆把268，269，270行删除，再截图过来。
![image](https://user-images.githubusercontent.com/25380989/64230250-d7eb4780-cf1e-11e9-8365-2200ffecc3b6.png)

**Comment by iamvicliu** [comment]
你好，新的报错如下
————————

1.邮箱验证  2.手机验证
请选择登录验证方式：2
已经发送验证码给：186***~~~
手机验证码：845160
Exceeded 30 redirects.

**Comment by Aruelius** [comment]
你好，我刚测试过，两个账号是没有问题的，你这种问题是因为百度的某个机制，会一直重定向，导致脚本报错，你可以把脚本删除，重新git clone 一下。
注意`config.py`的配置不要配置错。

**Comment by iamvicliu** [comment]
哈喽。我发现问题了，还是因为百度安全限制导致的。

**Comment by iamvicliu** [comment]
百度一直让我安全验证，就算浏览器登录也一样
——————
如您未开通登录保护，登录时系统提示需要进行安全验证，该验证无法人为取消，非常抱歉给您带来不便。感谢您对百度产品的信任与支持！

**Comment by vicliu1990** [comment]
一直让我安全验证

**Comment by Aruelius** [comment]
破案
