### ISSUE TITLE
打码平台报500错误

### ISSUE THREAD

**Issue by nvv5** [Aruelius/tieba_sign#8]
从cnn_captcha那里看到你的百度验证码识别的，想试一下用你的脚本结果验证码打码平台报500的错
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
你的接口和他原来项目的使用方式有改动？

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/65375695-02812280-dccb-11e9-87f9-24851c88c86b.png)

**Comment by nvv5** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/25380989/65375695-02812280-dccb-11e9-87f9-24851c88c86b.png)

我是用的POST方法会报500，代码是按你的来的，只是验证码图片随便找的，get型确实会报405，我在想是因为图片长宽不符合吗，您可以给一个可以正常识别的验证码吗，不清楚什么问题造成的

**Comment by Aruelius** [comment]
我这个模型是训练的百度贴吧的验证码的。

**Comment by nvv5** [comment]
> 
> 
> 我这个模型是训练的百度贴吧的验证码的。

我知道，因为百度系的验证码是差不多，但是web端改了验证方式，我就从网盘截图了一个验证码，结果发现一直报500，可以加个联系方式

**Comment by Aruelius** [comment]
https://github.com/Aruelius/tieba_sign/blob/4d129be9164b8eb702f476f4bc99b2802f423f0c/tieba_sign.py#L330
看这个函数

**Comment by nvv5** [comment]
> 
> 
> https://github.com/Aruelius/tieba_sign/blob/4d129be9164b8eb702f476f4bc99b2802f423f0c/tieba_sign.py#L330
> 
> 看这个函数

![图片](https://user-images.githubusercontent.com/35370503/65375998-99e77500-dccd-11e9-86d4-e1e5a428700c.png)
这是我改动了一点，理论上和官方是一样写得，但是会报错

**Comment by Aruelius** [comment]
![image](https://user-images.githubusercontent.com/25380989/65376029-e5018800-dccd-11e9-831b-5d3ae604a997.png)
 这是验证码

**Comment by nvv5** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/25380989/65376029-e5018800-dccd-11e9-831b-5d3ae604a997.png)
> 这是验证码

谢谢您，解决了，是因为长宽写死了。必须是180 40才行。

**Comment by Aruelius** [comment]
对的
