### ISSUE TITLE
系统繁忙，请稍后再试 请检查一下账号密码是否正确!

### ISSUE THREAD

**Issue by chendijun527** [Aruelius/tieba_sign#9]
使用教程操作安装
账号密码没问题，网页登陆成功
好像cookie都没获取成功，没有生成.user文件

**Comment by Aruelius** [comment]
cookie文件是隐藏文件
Linux使用`ll -a`查看隐藏文件

**Comment by chendijun527** [comment]
嗯，没有隐藏文件.user文件
我看代码好像是login函数里if codeStrin走else语句，然后二次验证TwoVerify函数里
if json1['msg'] == '系统繁忙，请稍后再试': 这里卡住了
也有可能是我账号的问题，我网页登陆要手机验证码加旋转图像验证码。
还有.user这个文件里cookie的格式是怎么样的，能不能手工从chrome里获取然后整合下直接写入.user这个文件

**Comment by Aruelius** [comment]
你可以截个图给我

**Comment by chendijun527** [comment]
运行报错
![uSJQL4.jpg](https://s2.ax1x.com/2019/09/22/uSJQL4.jpg)
手工网页登陆
先旋转图片验证码![uSJKQU.jpg](https://s2.ax1x.com/2019/09/22/uSJKQU.jpg)
后手机验证码![uSJMyF.jpg](https://s2.ax1x.com/2019/09/22/uSJMyF.jpg)

**Comment by Aruelius** [comment]
检查一下账号密码

**Comment by chendijun527** [comment]
我直接复制粘贴的，手工网页都能登陆。
我又调试了下，def getToken():这里返回值token为空，上面r返回的html源码好像是网页不存在(中文显示“拷锟矫”，好像编码gbk，英文显示正常)
![uStV2V.jpg](https://s2.ax1x.com/2019/09/22/uStV2V.jpg)

**Comment by Aruelius** [comment]
我今天起床测试一下。

**Comment by nicolasmeng** [comment]
一样的，那个 滑动验证是新出的，贴吧不好搞了...

**Comment by nicolasmeng** [comment]
> 嗯，没有隐藏文件.user文件
> 我看代码好像是login函数里if codeStrin走else语句，然后二次验证TwoVerify函数里
> if json1['msg'] == '系统繁忙，请稍后再试': 这里卡住了
> 也有可能是我账号的问题，我网页登陆要手机验证码加旋转图像验证码。
> 还有.user这个文件里cookie的格式是怎么样的，能不能手工从chrome里获取然后整合下直接写入.user这个文件

也想看看这个.user文件格式，手动复制下来，调试下后面的步骤

**Comment by Aruelius** [comment]
.user格式`{"BAIDUID": "", "BDUSS": "", "PTOKEN": "",  "STOKEN": ""}`

看了一下，确实是有点问题，在解决。

**Comment by Aruelius** [comment]
目前百度在获取tk ds参数的时候，加入了一个fs参数，这个fs如果不带，获取出来的tk ds是无效的。
暂时还是先用cookie。

**Comment by nicolasmeng** [comment]
没拿到cookie，登陆的时候怎么办呢？那个拖动的验证码必须要用浏览器了？

**Comment by Aruelius** [comment]
没拿到cookie没法登陆了，我昨天看过几种登陆方法：短信验证码登陆，手机贴吧登陆，网页登陆。
其中，网页登陆要拖动图片转向，这个是js判断的，如果转向好了，js会直接发送一个请求，来得到tk ds。
短信验证码跟手机贴吧账号密码登陆，都是js生成一个fs参数，viewlogAPI带上第一次请求到的参数加上fs参数再请求一次，才能继续，不然无限报验证码错误。

综上，目前只能自己填cookie文件了。

等我有时间可以研究一下这个二维码登录，不过二维码有可能也会要一些奇怪的参。

**Comment by nicolasmeng** [comment]
那签到是不是也有这种拖动验证码？

网易新出的airtestIDE,可以写登陆辅助。还能模拟手机端有界面操作，神器，就是慢，号少的还行

**Comment by chendijun527** [comment]
> .user格式`{"BAIDUID": "", "BDUSS": "", "PTOKEN": "", "STOKEN": ""}`
> 
> 看了一下，确实是有点问题，在解决。

现在只能手工填.user文件了，速度挺快的。
![2019-9-27 1-21-15.jpg](https://i.loli.net/2019/09/27/ZzaDIfkH6iCEvrB.jpg)
![2019-9-27 1-24-54.jpg](https://i.loli.net/2019/09/27/uDYEqGOH4T8lvbf.jpg)

**Comment by Aruelius** [comment]
@chendijun527 @nicolasmeng 已经更新登陆块，使用了半手动的扫码登陆。
